[theme]
base="light"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true

[menu]
showShareButton = false
showGetHelp = false
showAbout = false
